from libqtile.config import Key
from libqtile.command import lazy
mod = "mod4"
keys = [
    Key([mod], "Left", lazy.layout.left(), desc="Move focus to left"),
    Key([mod], "Right", lazy.layout.right(), desc="Move focus to right"),
    Key([mod], "Down", lazy.layout.down(), desc="Move focus down"),
    Key([mod], "Up", lazy.layout.up(), desc="Move focus up"),
    Key([mod,"control"], "space", lazy.layout.next(),
        desc="Move window focus to other window"),
    Key([mod, "shift"], "Left", lazy.layout.shuffle_left(),
        desc="Move window to the left"),
    Key([mod, "shift"], "Right", lazy.layout.shuffle_right(),
        desc="Move window to the right"),
    Key([mod, "shift"], "Down", lazy.layout.shuffle_down(),
        desc="Move window down"),
    Key([mod, "shift"], "Up", lazy.layout.shuffle_up(), desc="Move window up"),
    Key([mod, "control"], "Left", lazy.layout.grow_left(),
        desc="Grow window to the left"),
    Key([mod, "control"], "Right", lazy.layout.grow_right(),
        desc="Grow window to the right"),
    Key([mod, "control"], "Down", lazy.layout.grow_down(),
        desc="Grow window down"),
    Key([mod, "control"], "Up", lazy.layout.grow_up(), desc="Grow window up"),
    Key([mod,"control"], "d", lazy.layout.normalize(), desc="Reset all window sizes"),
    Key([mod, "shift"], "Return", lazy.layout.toggle_split(),
        desc="Toggle between split and unsplit sides of stack"),
    Key(["control"], "space", lazy.spawn('kitty'), desc="Launch terminal"),
    Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([mod], "c", lazy.window.kill(), desc="Kill focused window"),
    Key([mod,"control"], "f", lazy.window.toggle_floating(), desc="Stack To Float, Float to stack"),
    Key([mod, "control"], "r", lazy.restart(), desc="Restart Qtile"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
    Key([mod], "space", lazy.spawn('rofi -show drun -show-icons -theme sm'),
        desc="Spawn a command using a prompt widget"),
    Key([mod,"shift"],"e", lazy.spawn('rofi -show emoji -modi emoji -theme sm'),
        desc="Emoji Picker"),
    Key([mod], "b",lazy.spawn('brave'),desc="Browser"),
  Key([mod],"v",lazy.spawn('copyq menu'), desc="Clipboard popup"),
    Key([mod,"control"], "j", lazy.spawn( "pactl set-sink-volume @DEFAULT_SINK@ -5%")),
       Key([mod,"control"], "k",lazy.spawn( "pactl set-sink-volume @DEFAULT_SINK@ +5%")),
      Key([mod,"shift"], "a", lazy.spawn("brightnessctl set +10%")),
     Key([mod, "shift"], "d",lazy.spawn("brightnessctl set 10%-")),
    Key([mod],"F1",lazy.spawn("SoundWireServer -nogui")),
  Key([mod],"F2",lazy.spawn("killall -q SoundWireServer")),
Key([],"Print",lazy.spawn("flameshot gui")),
Key([mod],"e",lazy.spawn("kitty .config/vifm/scripts/vifmrun")),
Key([mod],"f",lazy.spawn("thunar")),
Key([mod,"control"],"n",lazy.spawn("kitty -e nmtui")),
Key([mod,"control"],"p",lazy.spawn("killall -q picom")),
Key([],"F3", lazy.spawn("picom")),
Key([mod],"l",lazy.spawn("betterlockscreen -l")),
Key([mod,"control"],"d",lazy.spawn("sh /home/kurama/.config/qtile/scripts/cbg.sh")),
]
